# Welcome to Jekyll! The static website generator.

port: 4000
livereload: true
reload_port: 5678

title: MangiarBene
email: pieter@roozen.nl
description: Jekyll version of Jekyll/React API endpoint demo 
baseurl: 
url:  
absolute_url:  

google_analytics: 

# Build settings
markdown: kramdown

exclude: [
README.md,
Gemfile,
Gemfile.lock,
]

gems:
  - jekyll-sitemap
  - jekyll-autoprefixer

autoprefixer:
  only_production: true
# $ JEKYLL_ENV=production bundle exec jekyll build

collections:
  books:
    output: true
    permalink: /books/:path/
  recipes:
    output: true
    permalink: /recipes/:path/

defaults:
  -
    scope:
      path: ""
      type: "books"
    values:
      layout: layout-books
  -
    scope:
      path: ""
      type: "recipes"
    values:
      layout: layout-recipes
